# Generated by Django 3.2.3 on 2021-06-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='college',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='year_study',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
