# Generated by Django 3.2.3 on 2021-06-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210610_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='average_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='total_quizzes_given',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
