# Generated by Django 3.2.3 on 2021-06-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_score_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='Score',
        ),
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
