# Generated by Django 3.2.2 on 2021-05-26 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.IntegerField()),
                ('quiz_title', models.CharField(max_length=200)),
                ('cover_img', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('option 1', 'option 1'), ('option 2', 'option 2'), ('option 3', 'option 3'), ('option 4', 'option 4'), ('option 5', 'option 5'), ('option 6', 'option 6'), ('option 7', 'option 7')], default=models.CharField(max_length=200), max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 26, 23, 27, 34, 482700)),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=10),
        ),
    ]
