# Generated by Django 3.2.3 on 2021-05-28 17:50

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20210526_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('option 1', 'option 1'), ('option 2', 'option 2'), ('option 3', 'option 3'), ('option 4', 'option 4'), ('option 5', 'option 5'), ('option 6', 'option 6'), ('option 7', 'option 7')], default=models.CharField(max_length=200), max_length=62),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 28, 23, 20, 13, 88342)),
        ),
    ]
