# Generated by Django 3.2.3 on 2021-05-28 19:11

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_question_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('option 1', 'option 1'), ('option 2', 'option 2'), ('option 3', 'option 3'), ('option 4', 'option 4'), ('option 5', 'option 5'), ('option 6', 'option 6'), ('option 7', 'option 7')], max_length=62),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 29, 0, 41, 15, 647096)),
        ),
    ]
