# Generated by Django 3.2.3 on 2021-06-01 18:23

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_alter_question_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('option 1', 'A'), ('option 2', 'B'), ('option 3', 'C'), ('option 4', 'D'), ('option 5', 'E'), ('option 6', 'F'), ('option 7', 'G')], max_length=62),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 1, 23, 53, 8, 9679)),
        ),
    ]
