# Generated by Django 3.2.3 on 2021-06-01 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_auto_20210601_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 2, 0, 37, 29, 502623)),
        ),
    ]
