# Generated by Django 3.2.3 on 2021-06-01 19:10

import builtins
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_alter_question_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 2, 0, 40, 11, 158702)),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz_id',
            field=models.IntegerField(default=builtins.id),
        ),
    ]
