# Generated by Django 3.2.3 on 2021-06-03 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_auto_20210602_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 3, 18, 2, 55, 556278)),
        ),
    ]
