# Generated by Django 3.2.3 on 2021-06-09 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0015_alter_question_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 9, 20, 17, 3, 111528)),
        ),
        migrations.AlterField(
            model_name='question',
            name='prob_img_1',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='prob_img_2',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='prob_img_3',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='cover_img',
            field=models.ImageField(blank=True, default='aaaaaaa.jpeg', upload_to='photos/%y/%m/'),
        ),
    ]
